const listaProdutos = [
  {
    id_produto: 1,
    id_categoria: 1,
    descricao: "Geladeira Brastemp Frost Free Inverse - Prata",
    preco: 5999,
    imagem: "./imgs/produtos/Geladeira_Brastemp_Prata.jpeg",
    categoria: "Geladeira",
  },
  {
    id_produto: 2,
    id_categoria: 1,
    descricao: "Geladeira Consul Frost Free - Prata",
    preco: 3999,
    imagem: "./imgs/produtos/Geladeira_Consul.jpeg",
    categoria: "Geladeira",
  },
  {
    id_produto: 3,
    id_categoria: 1,
    descricao: "Geladeira Brastemp Frost Free Inverse - Branca",
    preco: 4999,
    imagem: "./imgs/produtos/Geladeira_Brastemp_Branca.jpeg",
    categoria: "Geladeira",
  },
  {
    id_produto: 4,
    id_categoria: 2,
    descricao: "Fogão Atlas 4 Bocas Tropical Glass - Branco",
    preco: 699,
    imagem: "./imgs/produtos/Fog%C3%A3o_Atlas.jpeg",
    categoria: "Fogão",
  },
  {
    id_produto: 5,
    id_categoria: 2,
    descricao: "Fogão Consul 4 Bocas com Acendimento Automático",
    preco: 499,
    imagem: "./imgs/produtos/Fog%C3%A3o_Consul.jpeg",
    categoria: "Fogão",
  },
  {
    id_produto: 6,
    id_categoria: 3,
    descricao: "Máquina de Lavar Brastemp e Lavagem mais rápida",
    preco: 1499,
    imagem: "./imgs/produtos/Lava_Roupa_Brastemp.jpeg",
    categoria: "Maquina de Lavar",
  },
  {
    id_produto: 7,
    id_categoria: 3,
    descricao: "Máquina de Lavar Philco e Enxágue rápido",
    preco: 1999,
    imagem: "./imgs/produtos/Lava_Roupa_Philco.jpeg",
    categoria: "Maquina de Lavar",
  },
  {
    id_produto: 8,
    id_categoria: 3,
    descricao: "Máquina de Lavar 15kg Enxágue Anti-Alérgico",
    preco: 1999,
    imagem: "./imgs/produtos/Lavadoura_Brastemp.jpeg",
    categoria: "Maquina de Lavar",
  },
  {
    id_produto: 9,
    id_categoria: 4,
    descricao: "Micro-ondas Electrolux MEF41 menoe radioativo",
    preco: 499,
    imagem: "./imgs/produtos/Micro_ElectroLux.jpeg",
    categoria: "Micro-ondas",
  },
  {
    id_produto: 10,
    id_categoria: 4,
    descricao: "Micro-ondas Consul ainda menos radioativo",
    preco: 699,
    imagem: "./imgs/produtos/Micro_Ondas_Consul.jpeg",
    categoria: "Micro-ondas",
  },
  {
    id_produto: 11,
    id_categoria: 4,
    descricao: "Micro-ondas Philco sem radiação 2020",
    preco: 250,
    imagem: "./imgs/produtos/Micro_Philco.jpeg",
    categoria: "Micro-ondas",
  },
  {
    id_produto: 12,
    id_categoria: 5,
    descricao: "Freezer Electrolux FE26 Cycle Defrost - 203L",
    preco: 999,
    imagem: "./imgs/produtos/Freezer_Electrolux.jpeg",
    categoria: "Freezer",
  },
];

export default listaProdutos;